# Generated by Django 5.0.6 on 2024-05-19 07:51

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.CharField(max_length=12, verbose_name="Лицевой счет"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("electricity", "Электроснабжение"),
                            ("gas", "Газоснабжение"),
                            ("water", "Водоснабжение"),
                        ],
                        max_length=12,
                        verbose_name="Тип лицевого счета",
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("RUB", "Рубль")],
                        default="RUB",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Сумма задолженности",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено"),
                ),
            ],
            options={
                "verbose_name": "Задолженность",
                "verbose_name_plural": "Задолженности",
            },
        ),
        migrations.AddConstraint(
            model_name="debt",
            constraint=models.UniqueConstraint(
                fields=("type", "account"), name="unique_account_per_type"
            ),
        ),
    ]
