# Generated by Django 5.0.6 on 2024-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_electricity_account_user_gas_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="electricity_account",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Лицевой счет по электроснабжению",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gas_account",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Лицевой счет по газоснабжению",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="water_account",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Лицевой счет по водоснабжению",
            ),
        ),
    ]
